### PR TITLE
Fix deletion on update in gazetteer

### LINKED ISSUE #964: osm2pgsql hangs in gazetteer mode on diff
Last night osm2pgsql hung on both Nominatim servers on the following change: http://lonvia.de/attic/hanging-change-191028.osc There was no activity from osm2pgsql anymore. Last output:

```
Parsing gazetteer style file '/srv/nominatim.openstreetmap.org/nominatim/settings/import-full.style'.
Using projection SRS 4326 (Latlong)

Reading in file: /srv/nominatim.openstreetmap.org/bin/osmosischange.osc
Using XML parser.
Processing: Node(4k 4.2k/s) Way(0k 0.79k/s) Relation(20 2.50/s))
```

Postgresql activity logs show that [relation 9718561 version 5](https://www.openstreetmap.org/relation/9718561) was likely last processed. Restarting the updates helped as a workaround.

The tile servers are fine, so I suppose it is a gazetteer-specific issue.

### PR DESCRIPTION
**Pull request by lonvia**
Objects so far have been deleted directly from the main thread in gazetteer. This may lead to deadlock as the updates in the copy thread trigger SQL triggers which may touch an object currently being deleted.

Gazetteer objects are now deleted in the copy thread in a batch just like we do for all other tables. For this we need a different kind of deleter as the primary key is different for gazetteer's place table. For this, delete lists become first class objects and the copy manager becomes responsible for adding the right deleter to the copy buffer object.

Fixes #964.

### CODE REVIEW

File: src/db-copy.cpp [hunk 1]
```diff
@@ -119,24 +118,19 @@ void db_copy_thread_t::write_to_db(db_cmd_copy_t *buffer)
...
-    sql.reserve(buffer->target->name.size() + buffer->deletables.size() * 15 +
-                30);
-    sql += buffer->target->name;
-    sql += " WHERE ";
-    sql += buffer->target->id;
-    sql += " IN (";
-    for (auto id : buffer->deletables) {
-        sql += std::to_string(id);
+    std::string sql = "DELETE FROM {} WHERE {} IN ("_format(table, column);
+    sql.reserve(m_deletables.size() * 15 + sql.size());
```
Comment (joto) [inline src/db-copy.cpp]: Unexplained magic value 15 / unexplained calculation.

File: src/db-copy.cpp [hunk 2]
```diff
@@ -119,24 +118,19 @@ void db_copy_thread_t::write_to_db(db_cmd_copy_t *buffer)
...
+
+    for (auto id : m_deletables) {
+        sql += fmt::to_string(id);
```
Comment (joto) [inline src/db-copy.cpp]: This will create a string for each id and then append it. Consider using `fmt::basic_memory_buffer` or `fmt::format_to` with `back_inserter`.

File: src/gazetteer-style.cpp [hunk 3]
```diff
@@ -48,20 +61,26 @@ void gazetteer_style_t::clear()
...
-            if (std::get<2>(e) & SF_MAIN_NAMED) {
-                return !m_names.empty();
-            }
-            // XXX should handle SF_MAIN_NAMED_KEY as well
+    std::string l;
 
-            return true;
+    for (auto const &m : m_main) {
+        bool do_include = true;
+        if (std::get<2>(m) & SF_MAIN_NAMED) {
```
Comment (joto) [inline src/gazetteer-style.cpp]: Why the `do_include`? What's up with the `XXX`?

File: src/gazetteer-style.cpp [hunk 4]
```diff
@@ -48,20 +61,26 @@ void gazetteer_style_t::clear()
...
+        // XXX should handle SF_MAIN_NAMED_KEY as well
 
-        return false;
-    });
+        if (do_include) {
+            l += "'{}',"_format(std::get<0>(m));
+        }
+    }
+
+    if (!l.empty())
```
Comment (joto) [inline src/gazetteer-style.cpp]: {}

File: src/output-gazetteer.hpp [hunk 5]
```diff
@@ -108,23 +107,19 @@ class output_gazetteer_t : public output_t
...
-    void delete_place(char const *osm_type, osmid_t osm_id);
     int process_node(osmium::Node const &node);
     int process_way(osmium::Way *way);
     int process_relation(osmium::Relation const &rel);
     void connect();
 
-    void prepare_query_conn() const;
-
     void delete_unused_full(char const *osm_type, osmid_t osm_id)
     {
```
Comment (joto) [inline src/output-gazetteer.hpp]: Why is the parameter here a `char const *`, but `delete_object()` uses a `char`?

File: src/db-copy.cpp (hunk 1 above)
Comment (lonvia) [reply src/db-copy.cpp]: Added a comment.

File: src/db-copy.cpp (hunk 2 above)
Comment (lonvia) [reply src/db-copy.cpp]: Aha, that's where the additional second in the regression tests went. Switched to `fmt::memory_buffer` (also below). The `back_inserter` doesn't seem to be necessary. Compile-time strings only work with the FMT_STRING() macro in this constellation. That's mildly annoying.

File: src/gazetteer-style.cpp (hunk 3 above)
Comment (lonvia) [reply src/gazetteer-style.cpp]: Because I thought the if would be too complicated once the XXX is solved. On further thinking, the XXX needs to be solved in a totally different place. Something for another PR. (Note that the XXX was there before, so no regression here.)

File: src/gazetteer-style.cpp (hunk 4 above)
Comment (lonvia) [reply src/gazetteer-style.cpp]: Done.

File: src/output-gazetteer.hpp (hunk 5 above)
Comment (lonvia) [reply src/output-gazetteer.hpp]: It was historically easier to use. No longer necessary, made it a char parameter.
